openapi: 3.0.2
info:
  x-fragment: true
  title: An include file to define common schemas.
  version: 1.0.0

paths: {}

components:
  schemas:
    AssetBase:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        tags:
          $ref: "#/components/schemas/Tags"

    AssetDetailsBase:
      allOf:
        - $ref: "#/components/schemas/AssetBase"
        - type: object
          properties:
            extended:
              type: object
              additionalProperties:
                type: object

    ListItem:
      allOf:
        - $ref: "#/components/schemas/AssetBase"
        - type: object

    PagedList:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/ListItem"

    Tags:
      type: array
      items:
        type: string

    Genres:
      type: array
      items:
        type: string

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        fields:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

