openapi: 3.0.2
info:
  x-fragment: true
  title: An include file to define common responses.
  version: 1.0.0

paths: {}

components:
  responses:
    BadRequest:
      description: Bad Request.
      content:
        application/json:
          schema:
            $ref: "common-schemas.yml#/components/schemas/Error"

    NotFound:
      description: A resource could not be found.
      content:
        application/json:
          schema:
            $ref: "common-schemas.yml#/components/schemas/Error"

    PagedResponse:
      description: A paged list of items.
      content:
        application/json:
          schema:
            $ref: "common-schemas.yml#/components/schemas/PagedList"